### ISSUE TITLE
Filepath validation

### ISSUE THREAD

**Issue by ckulkarni-cribl** [Ravi-D/Log-Collection-Simple-REST-API#5]
Hi Ravi,

Can we add some validations on filePath provided in the query? What're the ways would you like to restrict this parameter?
```
            string fullPath = logRequest.GetFullPath();
```

Also, would be great if we can use proper http response codes to indicate user error vs system error etc.

**Comment by Ravi-D** [comment]
I can look into it. Ideally, only valid fields would be used to generate the LogRequest class in the first place, hence this line should be safe. I can double check to make sure there are no gaps. 

I can extend the error handling at different places in the code to differentiate whether or not the offending exception was due to user v system error.
